name: Daily Trivia Generation

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 UTC daily
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate-trivia:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'  # Enables pip caching
    
    - name: Cache MeloTTS
      uses: actions/cache@v4
      id: cache-melotts
      with:
        path: |
          MeloTTS
          ~/.cache/unidic  # Cache the unidic download
        key: ${{ runner.os }}-melotts-${{ hashFiles('MeloTTS/**') }}
    
    - name: Cache apt packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: imagemagick ffmpeg
        version: 1.0
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install moviepy requests nltk
        
    - name: Install MeloTTS
      if: steps.cache-melotts.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/myshell-ai/MeloTTS.git
        cd MeloTTS
        pip install -e .
        python -m unidic download
        cd ..
    
    - name: Run trivia generator
      run: python trivia_generator.py
      
    - name: Upload video
      uses: actions/upload-artifact@v4
      with:
        name: trivia-video
        path: output/videos/*.mp4
        retention-days: 5
