name: Daily Trivia Generation

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 UTC daily
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate-trivia:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install and Configure ImageMagick
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick
        sudo sed -i 's/rights="none" pattern="@\*"/rights="read|write" pattern="@*"/' /etc/ImageMagick-6/policy.xml
        sudo sed -i 's/<policy domain="path" rights="none" pattern="@\*"/<policy domain="path" rights="read|write" pattern="@*"/' /etc/ImageMagick-6/policy.xml
        
    - name: Install FFmpeg
      run: |
        sudo apt-get install -y ffmpeg
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install MeloTTS
      run: |
        git clone https://github.com/myshell-ai/MeloTTS.git
        cd MeloTTS
        pip install -e .
        python -m unidic download
        cd ..
    
    - name: Run trivia generator
      run: python trivia_generator.py
      
    - name: Upload video
      uses: actions/upload-artifact@v4
      with:
        name: trivia-video
        path: output/videos/*.mp4
        retention-days: 3
